import { Injectable } from '@angular/core';
import { jsPDF } from 'jspdf';

import { DatePlan, RewardsRedemptionSummary } from '../../models/date-plan.model';
import { PartnerRelationship } from '../../models/partner-relationship.model';

export interface DatePlanPdfInput {
  id: string;
  title: string;
  description: string;
  dateTime: string | Date;
  location: string;
  relationshipType?: PartnerRelationship;
  partnerName?: string;
  budget?: number | null;
  notes?: string;
  luckyDiscountPercent?: number | null;
  rewardsRedemption?: RewardsRedemptionSummary | null;
}

@Injectable({
  providedIn: 'root'
})
export class DatePlanPdfService {
  buildPdfBlob(plan: DatePlanPdfInput): Blob {
    const doc = new jsPDF();
    const dateValue = plan.dateTime instanceof Date ? plan.dateTime : new Date(plan.dateTime);
    const formattedDate = Number.isNaN(dateValue.getTime())
      ? String(plan.dateTime)
      : dateValue.toLocaleString();

    let y = 18;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(20);
    doc.text('BowerBox Date Plan', 14, y);

    y += 10;
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    doc.text(`Plan ID: ${plan.id}`, 14, y);

    y += 12;
    doc.setTextColor(0);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text(plan.title, 14, y);

    y += 10;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(12);

    const lines: string[] = [
      `Relationship: ${this.relationshipLabel(plan.relationshipType)}`,
      `Date & time: ${formattedDate}`,
      `Location: ${plan.location}`
    ];

    if (plan.partnerName) {
      lines.push(`Partner: ${plan.partnerName}`);
    }

    if (plan.budget != null) {
      lines.push(`Budget: $${plan.budget}`);
    }

    if (plan.luckyDiscountPercent) {
      lines.push(`Lucky discount: ${plan.luckyDiscountPercent}% off your bill share`);
    }

    if (plan.rewardsRedemption) {
      lines.push(`Rewards redeemed: ${plan.rewardsRedemption.label}`);
    }

    for (const line of lines) {
      y = this.writeLine(doc, line, 14, y);
    }

    y += 4;
    doc.setFont('helvetica', 'bold');
    doc.text('Description', 14, y);
    y += 6;
    doc.setFont('helvetica', 'normal');
    y = this.writeParagraph(doc, plan.description, 14, y);

    if (plan.notes?.trim()) {
      y += 4;
      doc.setFont('helvetica', 'bold');
      doc.text('Notes', 14, y);
      y += 6;
      doc.setFont('helvetica', 'normal');
      y = this.writeParagraph(doc, plan.notes, 14, y);
    }

    y = Math.max(y + 8, 250);
    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text('Generated by BowerBox • Stored in Google Cloud Storage', 14, y);

    return doc.output('blob');
  }

  fromDatePlan(plan: DatePlan): DatePlanPdfInput {
    return {
      id: plan.id,
      title: plan.title,
      description: plan.description,
      dateTime: plan.dateTime,
      location: plan.location,
      relationshipType: plan.relationshipType,
      partnerName: plan.partnerName,
      budget: plan.budget,
      notes: plan.notes,
      luckyDiscountPercent: plan.luckyDiscountPercent,
      rewardsRedemption: plan.rewardsRedemption
    };
  }

  private relationshipLabel(relationship?: PartnerRelationship): string {
    if (relationship === 'married') {
      return 'Married';
    }

    if (relationship === 'engaged') {
      return 'Engaged';
    }

    return 'Dating';
  }

  private writeLine(doc: jsPDF, text: string, x: number, y: number): number {
    const wrapped = doc.splitTextToSize(text, 180) as string[];
    doc.text(wrapped, x, y);
    return y + wrapped.length * 6;
  }

  private writeParagraph(doc: jsPDF, text: string, x: number, y: number): number {
    const wrapped = doc.splitTextToSize(text, 180) as string[];
    for (const line of wrapped) {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }

      doc.text(line, x, y);
      y += 6;
    }

    return y;
  }
}
